---
# Set a default sites path.
sites_path: '~/Sites'

# List sites, indexed by path to web root.
sites:
  /:
    - dent
    - eecs
    - eight
    - greenbiz
    - hsa
    - kalablog
    - kcom
    - msdw
    - seven
    - stamp
    - trulymad
    - usfi
  /web:
    - kalablog8
    - progmi
  /www:
    - accelerate
    - ctsi
  /docroot:
    - ucsf
  /public:
    - poets

# List multisites / sub-domains.
# @TODO break multisites and just extra sub-domains into separate variables so
# that we can know which need `sites.php` config (the former) and which don't
# (the latter). The `ucsf-multisite.yml` task and `ucsf--local.sites.inc.j2`
# template are currently hard-coded to act on the UCSF site only.
multisites:
  eecs:
    - ee
    - cs
  ucsf:
    - nursing
    - silvermandigitallibrary
  ctsi:
    - open-proposals
    - mosaic
